'''
@author: giuliacarla
'''


import numpy as np
import astropy.units as u


class GuideSource():
    '''
    This class defines the geometry of the guide source of interest.

    Parameters
    ----------
    polar_coords: tuple of two floats
        Source polar coordinates (rho, theta) in [arcsec, degrees].
        theta is positive if generated by a counterclockwise rotation.

    height: float
        Source height in [meters].
    '''

    def __init__(self, polar_coords, height):
        self._rho = polar_coords[0]
        self._theta = polar_coords[1]
        self._z = height

    @staticmethod
    def fromPolarToCartesian(rho, theta):
        x = rho * np.cos(theta)
        y = rho * np.sin(theta)
        return x, y

    def getSourceCartesianCoords(self):
        x, y = self.fromPolarToCartesian(self._rho, np.deg2rad(self._theta))
        return [x * u.arcsec, y * u.arcsec, self._z * u.m]

    def getSourcePolarCoords(self):
        return [self._rho * u.arcsec, self._theta * u.deg, self._z * u.m]
