'''
@author: giuliacarla
'''


import numpy as np


class GuideSource(object):
    '''
    This class defines the geometry of the guide source of interest.
    
    Parameters
    ----------
    polar_coords: tuple of two floats
        Source polar coordinates (rho, theta) in [arcsec, degrees].
        theta is positive if generated by a counterclockwise rotation.
        
    height: float
        Source height in [meters].   
    '''
    
    def __init__(self, polar_coords, height):
        self._rho = polar_coords[0]
        self._theta = polar_coords[1]
        self._z = height
        
    @staticmethod    
    def fromDegToRad(angle_deg):
        return angle_deg*np.pi/180
        
    @staticmethod    
    def fromPolarToCartesian(rho, thetaRad):
        x = rho*np.cos(thetaRad)
        y = rho*np.sin(thetaRad)
        return x, y
    
    def getSourceCartesianCoords(self):
        x, y = self.fromPolarToCartesian(self._rho,
                                         self.fromDegToRad(self._theta))
        return np.array([x, y, self._z])
    
    def getSourcePolarCoords(self):
        return np.array([self._rho, self._theta, self._z])